spring:
  application:
    name: helmify
  initializr:
    host: spring.helmify.me
  devtools:
    restart:
      additional-paths: src/main/resources/static
  threads:
    virtual:
      enabled: true

logging:
  level:
    web: DEBUG

management:
  server:
    port: 9090

