[http.middlewares.simpleAuth.basicAuth]
users = [
    "${TRAEFIK_BASIC_AUTH}"
]

[http.routers.api]
rule = "Host(`tfk.helm-start.com`)"
entrypoints = ["websecure"]
middlewares = ["simpleAuth"]
service = "api@internal"
[http.routers.api.tls]
certResolver = "lets-encrypt"
